name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: npm install
      
    - name: Build and Export
      run: npm run build
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages  # Branch para onde os arquivos serão enviados
        folder: out       # Pasta que contém os arquivos a serem publicados
